"""Does `alembic downgrade` actually work?

Nothing else in this repo answers that. The unit suite builds its schema with
``Base.metadata.create_all`` and stamps ``alembic_version`` by hand (see
conftest), and ``scripts/deploy_smoke.sh`` only ever ran ``upgrade head``. So
across 52 revisions no ``downgrade()`` had ever been executed automatically — a
broken one would first surface during a production rollback.

⚠️ THIS FILE IS THE DIALECT-AGNOSTIC HALF, AND IT IS NOT SUFFICIENT.

Written first against SQLite alone, the round-trip below passed cleanly while a
real defect sat in the initial migration: its ``downgrade()`` dropped the tables
but left the ``dbtype`` Postgres enum behind, so ``downgrade base`` followed by
``upgrade head`` died with ``type "dbtype" already exists``. SQLite renders
``sa.Enum`` as VARCHAR, so there was no type to leak and nothing to see — the
same blind spot that let the missing ``powerbi`` label ship for months
(c6d7e8f9a0b1). The Postgres half of this harness lives in
``scripts/deploy_smoke.sh``, which is the only place in CI with a real database.

Keep both. This one is free and runs on every push; that one is slow and is the
only one that can see a dialect.

Run out-of-process on purpose:

* ``env.py`` reads ``settings.DATABASE_URL`` and overwrites whatever
  ``sqlalchemy.url`` the caller set, so an in-process ``command.upgrade()``
  would migrate — and then downgrade — the suite's own database.
* ``env.py`` ends in ``asyncio.run(...)``, which raises inside a running loop.
* It exercises the literal command an operator types.
"""
from __future__ import annotations

import ast
import contextlib
import os
import sqlite3
import subprocess
import sys
from pathlib import Path

from cryptography.fernet import Fernet

BACKEND = Path(__file__).resolve().parents[1]
VERSIONS = BACKEND / "app" / "db" / "migrations" / "versions"

# What `alembic revision --autogenerate` writes into a body it had nothing to
# put in. Present in almost every migration here, so it cannot count as a human
# explaining a deliberate no-op.
#
# Matched as "a comment line mentioning this", and whole lines are dropped rather
# than the substring: the marker ends in `###`, so replacing the prefix left
# ` - please adjust! ###` behind — still a `#`, so the stub still read as
# explained. Measured; the first version of this constant did exactly that.
AUTOGEN_MARKER = "### commands auto generated by Alembic"
AUTOGEN_END = "### end Alembic commands ###"


def _alembic(db_path: Path, *args: str) -> subprocess.CompletedProcess[str]:
    """Run alembic against `db_path` and nothing else."""
    env = {
        **os.environ,
        # The override that matters. conftest points DATABASE_URL at the shared
        # test database, and app/config.py falls back to `./nexusbi.db` — the
        # developer's own database, relative to the cwd this subprocess uses.
        # Losing this line means `downgrade base` lands on one of those two.
        "DATABASE_URL": f"sqlite+aiosqlite:///{db_path}",
        # Same reason conftest sets it: a developer's repo-root .env must not
        # reconfigure a run that CI performs without one.
        "NEXUSBI_IGNORE_DOTENV": "1",
        "SECRET_KEY": "migration-roundtrip-secret-at-least-32-chars",
        # Minted, not copied. The obvious move was to paste conftest's literal,
        # and gitleaks failed the build for it (generic-api-key, this line) —
        # correctly: a key-shaped constant is a scanner's job to flag whether or
        # not it is real, and the repo's .gitleaksignore silences findings by
        # fingerprint, so pasting it would have meant adding an entry to say "the
        # duplicate is fine". Generating removes the finding instead of muting it.
        # Settings only requires a well-formed key here; nothing encrypts.
        "FERNET_KEY": Fernet.generate_key().decode(),
        "DEMO_MODE": "true",
    }
    return subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=BACKEND,
        env=env,
        capture_output=True,
        text=True,
        timeout=300,
    )


def _fail(proc: subprocess.CompletedProcess[str], what: str) -> str:
    # stdout FIRST, and never stdout alone-or-stderr alone: alembic's `util.err`
    # path writes the one useful line ("FAILED: Can't locate revision …") to
    # stdout while stderr carries fifty INFO lines. Measured — an earlier version
    # of this file attached only stderr and would have reported a wall of
    # "Running upgrade X -> Y" with the reason missing.
    return f"{what}\n--- stdout ---\n{proc.stdout}\n--- stderr ---\n{proc.stderr}"


def _tables(db_path: Path) -> set[str]:
    # closing(), not just `with sqlite3.connect(...)`: the connection's context
    # manager is a TRANSACTION manager and leaves the handle open.
    with contextlib.closing(sqlite3.connect(db_path)) as conn:
        rows = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
        ).fetchall()
    return {r[0] for r in rows}


def _stat(path: Path) -> tuple[int, int] | None:
    return (path.stat().st_mtime_ns, path.stat().st_size) if path.exists() else None


def test_upgrade_downgrade_upgrade_is_clean(tmp_path: Path) -> None:
    from app.db.base import Base

    db = tmp_path / "roundtrip.db"
    # The two databases this test must never touch. `nexusbi.db` is app/config's
    # default and therefore where a lost DATABASE_URL override lands — it is a
    # real developer database, tens of megabytes of it. Asserting on the files
    # is the point: an earlier version asserted that the env string it had just
    # built did not contain "test_nexusbi", which re-checked its own input and
    # could not have failed.
    #
    # Exact under `pytest -q`, which is what CI runs: between the snapshot and
    # the check only this test's subprocess executes. A parallel runner would
    # need this narrowed to `nexusbi.db`, since a sibling worker legitimately
    # writes the suite's own database.
    guarded = {p: _stat(p) for p in (BACKEND / "nexusbi.db", BACKEND / "test_nexusbi.db")}

    up1 = _alembic(db, "upgrade", "head")
    assert up1.returncode == 0, _fail(up1, "first upgrade failed")
    # Checked BEFORE the schema assertion, so that losing the override reports
    # "it ran against nexusbi.db" rather than the downstream "the temp database
    # is empty" — measured by deleting the DATABASE_URL line, which without this
    # ordering failed on the table-set comparison and named the wrong cause.
    for path, before in guarded.items():
        assert _stat(path) == before, f"the migration ran against {path.name}, not the temp database"

    after_first = _tables(db)
    # Exact, not a magic "more than 20". If the upgrade quietly built nothing —
    # or built it somewhere else — every comparison below would hold between two
    # wrong values.
    assert after_first == set(Base.metadata.tables) | {"alembic_version"}

    down = _alembic(db, "downgrade", "base")
    assert down.returncode == 0, _fail(down, "downgrade base failed")
    # `alembic_version` survives by design — alembic keeps its own bookkeeping
    # table. Everything the application owns must be gone.
    assert _tables(db) == {"alembic_version"}, "downgrade base left application tables behind"

    up2 = _alembic(db, "upgrade", "head")
    assert up2.returncode == 0, _fail(
        up2, "the schema cannot be rebuilt after a full rollback — this is what a rollback would hit"
    )
    # Table names only. That catches a downgrade which forgets a table, which is
    # the common shape; it does NOT prove column-level equality — a downgrade
    # that loses a column type or an index rebuilds the same names. Postgres
    # column-level equality is what check_schema_drift.py in deploy_smoke.sh is
    # for.
    assert _tables(db) == after_first


def test_one_migration_head() -> None:
    """Two heads mean an unmerged branch, and `upgrade head` becomes ambiguous.

    Calls the production helper rather than rebuilding its Config: this is the
    function behind ``"migrations":"ok"`` in /ready, which deploy_smoke.sh
    asserts on. A copy of it here would leave the real one untested.
    """
    from app.core.health import _migration_heads

    heads = _migration_heads()
    assert len(heads) == 1, f"expected a single head, found {sorted(heads)}"


def _downgrade_fn(tree: ast.Module) -> ast.FunctionDef | ast.AsyncFunctionDef | None:
    return next(
        (
            n
            for n in tree.body
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name == "downgrade"
        ),
        None,
    )


def test_every_revision_defines_a_downgrade() -> None:
    """A `downgrade()` that was never written is a rollback that cannot happen.

    Deliberately weaker than "every downgrade reverses its upgrade" — one of them
    legitimately cannot (c6d7e8f9a0b1: Postgres has no DROP VALUE for an enum
    label). This insists only that a no-op is a decision someone wrote down.

    ⚠️ Three things this got wrong on the first attempt, each measured against a
    crafted stub rather than argued about:

    * The canonical unfinished migration is not a bare ``pass`` — it is the
      ``pass`` between Alembic's own ``# ###`` markers, which any "is there a
      comment?" test reads as explained. That stub is now excluded explicitly.
    * ``ast.get_source_segment`` stops at the function's ``end_col_offset``, so
      ``pass  # nothing to reverse`` loses its comment and a correctly documented
      no-op was flagged. The raw lines are read instead.
    * ``return`` and ``raise NotImplementedError`` are no-ops too, and
      ``async def downgrade`` is not an ``ast.FunctionDef``.
    """
    missing: list[str] = []
    for path in sorted(VERSIONS.glob("*.py")):
        source = path.read_text(encoding="utf-8")
        lines = source.splitlines()
        fn = _downgrade_fn(ast.parse(source))
        if fn is None:
            missing.append(f"{path.name}: no downgrade()")
            continue

        body = [n for n in fn.body if not (isinstance(n, ast.Expr) and isinstance(n.value, ast.Constant))]
        is_noop = all(
            isinstance(n, ast.Pass)
            or (isinstance(n, ast.Return) and n.value is None)
            or (isinstance(n, ast.Raise) and isinstance(n.exc, ast.Call)
                and getattr(n.exc.func, "id", "") == "NotImplementedError")
            for n in body
        )
        if not is_noop:
            continue

        # fn.lineno is 1-based and points at `def`; end_lineno covers the body.
        block = [
            line
            for line in lines[fn.lineno - 1 : fn.end_lineno or fn.lineno]
            if AUTOGEN_MARKER not in line and AUTOGEN_END not in line
        ]
        if not any("#" in line for line in block) and not ast.get_docstring(fn):
            missing.append(f"{path.name}: downgrade() does nothing, and does not say why")

    assert not missing, "\n".join(missing)


def _enum_names(node: ast.AST) -> set[str]:
    """Named enum types a migration body creates.

    `sa.Enum(..., name='x')` inside create_table or alter_column emits CREATE
    TYPE on Postgres. `create_type=False` says the caller is reusing a type
    somebody else owns, so it carries no obligation to drop it.
    """
    found: set[str] = set()
    for sub in ast.walk(node):
        if not isinstance(sub, ast.Call):
            continue
        # `sa.Enum` / `postgresql.ENUM` (Attribute) and a bare `Enum` from a
        # direct import (Name) — the convention here is the first, but a rule
        # that only understood it would go quiet on the day someone changes the
        # import style, which is the wrong way for a guard to fail.
        called = getattr(sub.func, "attr", None) or getattr(sub.func, "id", None)
        if called not in {"Enum", "ENUM"}:
            continue
        kwargs = {k.arg: k.value for k in sub.keywords}
        name = kwargs.get("name")
        if not isinstance(name, ast.Constant) or not isinstance(name.value, str):
            continue
        create = kwargs.get("create_type")
        if isinstance(create, ast.Constant) and create.value is False:
            continue
        found.add(name.value)
    return found


def test_every_created_enum_type_is_dropped_on_downgrade() -> None:
    """The defect the Postgres round-trip found, pinned as a CLASS.

    `sa.Enum(name='dbtype')` inside create_table emits CREATE TYPE on Postgres,
    but `op.drop_table('datasources')` takes a bare name with no metadata and
    leaves the type behind. Measured on a real Postgres probe: `downgrade base`
    then `upgrade head` failed with `type "dbtype" already exists`, i.e. a
    rollback made the database un-redeployable.

    ⚠️ The first version of this test asserted `"DROP TYPE IF EXISTS dbtype" in
    downgrade_source` for one hardcoded revision. Measured by mutation: commenting
    the statement out left the substring in the comment and ALL FOUR TESTS PASSED,
    and the SQLite round-trip cannot see the defect either — so the guard was
    decoration. It also would not have noticed the second migration to create an
    enum. Parsed, and over every revision, for both reasons.
    """
    offenders: list[str] = []
    for path in sorted(VERSIONS.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        up = next(
            (n for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name == "upgrade"),
            None,
        )
        down = _downgrade_fn(tree)
        if up is None or down is None:
            continue
        for name in sorted(_enum_names(up) - _enum_names(down)):
            offenders.append(
                f"{path.name}: upgrade() creates enum type '{name}', downgrade() never drops it"
            )

    assert not offenders, (
        "\n".join(offenders)
        + "\n\nAdd `sa.Enum(..., name=...).drop(op.get_bind(), checkfirst=True)` to downgrade(). "
        "It carries the dialect check and the IF EXISTS itself — a hand-written "
        "`op.execute('DROP TYPE ...')` has to get both right and is a syntax error on SQLite."
    )
