"""initial tables

Revision ID: 0189ecef4246
Revises: 
Create Date: 2026-06-24 23:17:55.601277
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0189ecef4246'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('dashboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_user_id'), ['user_id'], unique=False)

    op.create_table('datasources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('db_type', sa.Enum('postgresql', 'mysql', 'sqlite', name='dbtype'), nullable=False),
    sa.Column('connection_string_encrypted', sa.Text(), nullable=False),
    sa.Column('schema_cache', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasources_user_id'), ['user_id'], unique=False)

    op.create_table('query_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('datasource_id', sa.String(length=36), nullable=True),
    sa.Column('natural_language', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=False),
    sa.Column('chart_type', sa.String(length=50), nullable=False),
    sa.Column('chart_config', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_logs_user_id'), ['user_id'], unique=False)

    op.create_table('widgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dashboard_id', sa.String(length=36), nullable=False),
    sa.Column('query_log_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_log_id'], ['query_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widgets_dashboard_id'), ['dashboard_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widgets_dashboard_id'))

    op.drop_table('widgets')
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_logs_user_id'))

    op.drop_table('query_logs')
    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasources_user_id'))

    op.drop_table('datasources')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_user_id'))

    op.drop_table('dashboards')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###

    # Everything above is stock autogenerate, and stock autogenerate does not
    # know about this. `sa.Enum(..., name='dbtype')` inside create_table emits a
    # CREATE TYPE on Postgres, but `op.drop_table('datasources')` takes a bare
    # table name with no metadata attached, so it drops the table and leaves the
    # type. `alembic downgrade base` then succeeded while leaving `dbtype`
    # behind, and the next `alembic upgrade head` died on
    #
    #     type "dbtype" already exists
    #     [SQL: CREATE TYPE dbtype AS ENUM ('postgresql', 'mysql', 'sqlite')]
    #
    # i.e. a rollback to base made the database un-redeployable. Measured on a
    # real Postgres probe, not reasoned about.
    #
    # Invisible on SQLite, where sa.Enum renders as VARCHAR and there is no type
    # to leak — the same blind spot that let the missing `powerbi` label ship for
    # months (see c6d7e8f9a0b1). Which is why the round-trip is exercised against
    # a real Postgres in scripts/deploy_smoke.sh, and only the dialect-agnostic
    # half in the unit suite.
    #
    # `Enum.drop`, not `op.execute('DROP TYPE IF EXISTS dbtype')`: it carries the
    # dialect check (a no-op where the dialect has no native enum) and the
    # IF EXISTS (`checkfirst`) itself, so neither has to be hand-written and
    # neither can be hand-written wrong. The name here must keep matching the
    # `sa.Enum` in upgrade() — test_migrations_roundtrip pins that for every
    # migration, not just this one.
    sa.Enum('postgresql', 'mysql', 'sqlite', name='dbtype').drop(op.get_bind(), checkfirst=True)
